#!/usr/bin/env perl
use strict;
use warnings;
use autodie;

#my $url = 'http://reisingers.duckdns.org/~jreisinger/jobs-count.csv';
my $url;

system "prove -lvr" and die "Tests don't pass";

system "wget -O jobs-count.csv $url" if defined $url;

system "echo 'Date,Term,Count' > jobs-count_for-github.csv";
system "cat jobs-count.csv | sed 's/;/,/g' >> jobs-count_for-github.csv";

my %regex = (
    "Scripting languages" => '^(python|perl|ruby|shell|bash)$',
    "Operating systems"   => '^(linux|windows)$',
    "Certifications"      => '^(ccna|cissp|lpic)$',
    "Linux sysadmin"      => '^(linux perl|linux python|linux ruby)$',
    "Monitoring"          => '^(zabbix|nagios|icinga)$',
    "Databases"           => '^(mysql|postgresql|oracle)$',
    "Web servers"         => '^(apache|nginx|lighttpd)$',
    "Configuration mngt"  => '^(puppet|chef|salt|cfengine|ansible)$',
    "DevOps"              => '^(devops|cloud|aws|agile|scrum)$',
    "Other"               => '^(cluster|bind|haproxy|memcache|redis|jenkins|docker)$',
);

for my $title ( keys %regex ) {
    system "./gen-graph --select '$regex{$title}' --xskip 50 --title '$title'";
}

system "git commit -am 'updated data' && git push";
